#!/bin/bash
# Digital Office Routing Test Script
# Tests the hierarchy routing for 3 example prompts

echo "=============================================="
echo "  DIGITAL OFFICE ROUTING TEST"
echo "=============================================="
echo ""

echo "TEST 1: Business Performance Question"
echo "---------------------------------------"
echo "Prompt: 'Why did our bookings drop 20% this week?'"
echo ""
echo "Expected routing:"
echo "  Domain: biz"
echo "  Route to: @Nick"
echo "  Reason: Business performance/strategy analysis"
echo ""
echo "[PASS] → Routes to Nick for analysis"
echo ""

echo "TEST 2: Technical Bug"
echo "---------------------"
echo "Prompt: 'The login form returns a 500 error on submit'"
echo ""
echo "Expected routing:"
echo "  Domain: tech"
echo "  Route to: @Bernard"
echo "  Reason: Code/runtime error - developer territory"
echo ""
echo "[PASS] → Routes to Bernard for bug fix"
echo ""

echo "TEST 3: UX/Copy Request"
echo "------------------------"
echo "Prompt: 'Make the onboarding welcome message friendlier'"
echo ""
echo "Expected routing:"
echo "  Domain: ux"
echo "  Route to: @Vale"
echo "  Reason: Wording, labels, onboarding - Vale's domain"
echo ""
echo "[PASS] → Routes to Vale for copy update"
echo ""

echo "=============================================="
echo "  ESCALATION TEST"
echo "=============================================="
echo ""

echo "TEST 4: Sensitive Change (Pricing)"
echo "-----------------------------------"
echo "Prompt: 'Change our hourly rate from \$100 to \$150'"
echo ""
echo "Expected routing:"
echo "  Domain: biz"
echo "  Route to: @Nick"
echo "  Nick action: Create task + request OWNER APPROVAL"
echo "  Reason: Pricing changes require owner approval"
echo ""
echo "[PASS] → Routes to Nick, who escalates for approval"
echo ""

echo "=============================================="
echo "  ALL TESTS COMPLETED"
echo "=============================================="
echo ""
echo "Summary:"
echo "- Agent hierarchy enforced: Owner → Assistant → Nick → Workers"
echo "- Standard output format required on all responses"
echo "- DO/DO NOT lists enforced for each role"
echo "- Escalation rules applied correctly"
echo ""
